[graph]
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
]
confidence-threshold = 0.9
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
